compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]
name = "subscription"
main = "src/index.js"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "SUBSCRIPTION_MANAGEMENT"
id = "6aa7d075af61450f8fac02d0796cb011"

[[durable_objects.bindings]]
class_name = "Customer"
name = "CUSTOMER"

[[migrations]]
new_classes = ["Customer"]
tag = "v1"
