compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]
name = "subscription"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "SUBSCRIPTION_MANAGEMENT"
id = "6aa7d075af61450f8fac02d0796cb011"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
